I"{<ul>
  <li><strong>Origin</strong>:
    <ul>
      <li>The ValueError raised after typed <code class="highlighter-rouge">pip3 freeze &gt; requirements.txt&gt;</code> and it gave: <code class="highlighter-rouge">ValueError: ("Missing 'Version:' header and/or METADATA file", Unknown [unknown version] (c:\users\james\appdata\local\programs\python\python37\lib\site-packages))</code></li>
      <li>The error like:
  ```Exception:
  Traceback (most recent call last):
File “c:\users\james\appdata\local\programs\python\python37\lib\site-packages<br />
  pip_vendor\pkg_resources__init__.py”, line 2584, in version
  return self._version
File “c:\users\james\appdata\local\programs\python\python37\lib\site-packages<br />
  pip_vendor\pkg_resources__init__.py”, line 2691, in <strong>getattr</strong>
  raise AttributeError(attr)
  AttributeError: _version</li>
    </ul>
  </li>
</ul>
:ET